version: '3'
services:
  front-end:
    hostname: frontend
    image: dtdemos/dt-orders-frontend:1
    ports:
      - 80:8080
    environment:
      - CUSTOMER_URL=http://172.17.0.1:8181
      - CATALOG_URL=http://172.17.0.1:8182
      - ORDER_URL=http://172.17.0.1:8183
      - DT_CUSTOM_PROP=project=dt-orders stage=production service=frontend owner=app-team-2
      - DT_CLUSTER_ID=production-frontend
  customer-service:
    hostname: customer
    image: dtdemos/dt-orders-customer-service:1
    ports:
      - 8181:8080
    environment:
      - DT_CUSTOM_PROP=project=dt-orders stage=production service=customer-service owner=app-team-1
      - DT_CLUSTER_ID=production-customer-service
  catalog-service:
    hostname: catalog
    image: dtdemos/dt-orders-catalog-service:1
    ports:
      - 8182:8080
    environment:
      - DT_CUSTOM_PROP=project=dt-orders stage=production service=catalog-service owner=app-team-1
      - DT_CLUSTER_ID=production-catalog-service
  order-service:
    hostname: order
    image: dtdemos/dt-orders-order-service:1
    ports:
      - 8183:8080
    environment:
      - CUSTOMER_SERVICE_DOMAIN=172.17.0.1
      - CUSTOMER_SERVICE_PORT=8181
      - CATALOG_SERVICE_DOMAIN=172.17.0.1
      - CATALOG_SERVICE_PORT=8182
      - DT_CUSTOM_PROP=project=dt-orders stage=production service=order-service owner=app-team-1
      - DT_CLUSTER_ID=production-order-service
